### ISSUE TITLE
Unable to seed data in development...

### ISSUE THREAD

**Issue by jvenator** [hulihanapplications/Opal#16]
I successfully installed Opal and am able to access it locally. I attempted to seed the development database, but was unable to.

```
j(opal)$ bundle exec rake db:seed
/Users/j/.rvm/gems/ruby-1.9.2-p290@opal_0.8/gems/rack-1.3.4/lib/rack/backports/uri/common_192.rb:53: warning: already initialized constant WFKV_
Installing...rake aborted!
Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true

Tasks: TOP => db:seed
```

**Comment by jvenator** [comment]
I went ahead and tried everything on the production database. The first two steps (db:migrate and db:seed) worked, but still gave the "warning: already initialized constant WFKV_". However, the third step (assets:precompile) did not work. Perhaps this is because I ran it locally rather than on the production server (which will be Heroku). Regardless, here's what came through...

```
j(opal)$ bundle exec rake assets:precompile RAILS_ENV=production
/Users/j/.rvm/gems/ruby-1.9.2-p290@opal_0.8/gems/rack-1.3.4/lib/rack/backports/uri/common_192.rb:53: warning: already initialized constant WFKV_
/Users/j/.rvm/rubies/ruby-1.9.2-p290/bin/ruby /Users/j/.rvm/gems/ruby-1.9.2-p290@opal_0.8/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
```

**Comment by hulihanapplications** [comment]
You should be able to precompile assets locally. The `rake assets:precompile` usually doesn't output anything if it succeeds...Did anything get generated in `public/assets`?

**Comment by hulihanapplications** [comment]
Also, the error you're getting when trying to seed the development database is because `config.action_mailer.default_url_options` isn't set in the development environment. You can fix this by adding this `config/environments/development.rb`:

``` rb
  # Add default host for ActionMailer
  config.action_mailer.default_url_options = { :host => "localhost" }

```

I've added this to the dev branch in commit [4bcdad2](https://github.com/hulihanapplications/Opal/commit/4bcdad27093ed80c7d24f94bc51ad843691b9cb5). You may not want to pull all of the dev commits, since Opal 0.8.2's layout is currently broken. Thanks for reporting this, hope this helps.

**Comment by jvenator** [comment]
Thanks. By the way, this is all happening on the way to getting it installed and running on Heroku. It is honestly not going so smoothly. If you think my question is resolved go ahead and close this.

I can then go on the Opal dev site and just post something with all the Q's and issues I'm having.

**Comment by hulihanapplications** [comment]
Sorry you're having trouble with heroku, let me know of any other snags you're having, and I'll do what I can to help. Feel free to open tickets here on github or on the dev site.

**Comment by jvenator** [comment]
In answer to your question about public assets, yes, a bunch of files were added. I'm going to go ahead and close this issue and create one on the opal dev site that covers all of my issues at a high level. We can then break it up as needed. Thanks
