### ISSUE TITLE
Unable to create sub categories

### ISSUE THREAD

**Issue by ghost** [hulihanapplications/Opal#19]
Hi, I'm trying out Opal, it looks great but I have an issue where I am unable to create sub categories.

If I create a Category and set it to be a child of another and save, it appears at the top level.

I have also tried editing categories after creating them and have the same issue.

Importing the sample db I get the subcategories from the sample but am unable to change the category they are under.

Any help would be great.

regards

**Comment by hulihanapplications** [comment]
I've fixed this in commit [e6ca1e](https://github.com/hulihanapplications/Opal/commit/e6ca1e240c4b57f4831cfeafb4b2bd71714e37bb) and pushed it to the dev branch. Let me know how this works for you.

**Comment by ghost** [comment]
Many Thanks
