### ISSUE TITLE
Plugins Settings error

### ISSUE THREAD

**Issue by ghost** [hulihanapplications/Opal#20]
Hi, I have noticed another issue, when trying change settings on plugins I get the following error (I'm running the dev branch):

ActionView::MissingTemplate in Plugins#settings

Showing /usr/home/oggy/apps/Opal/app/views/settings/_list_settings.html.erb where line #11 raised:

Missing partial plugin_settings/plugin_setting with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :coffee]}. Searched in:
- "/usr/home/oggy/apps/Opal/public/themes/fracture/app/views"
- "/usr/home/oggy/apps/Opal/app/views"
  Extracted source (around line #11):

8: 
9:  <%= content_tag :div, :class => :settings do %>
10:         <% for setting in settings %>
11:             <%= render setting %>  
12:         <% end %>
13:     <% end %>
14: </div>
Trace of template inclusion: app/views/plugins/settings.html.erb

Rails.root: /usr/home/oggy/apps/Opal

Application Trace | Framework Trace | Full Trace
app/views/settings/_list_settings.html.erb:11:in `block (2 levels) in _app_views_settings__list_settings_html_erb__2294011647741628367_17629938240'
app/views/settings/_list_settings.html.erb:10:in`block in _app_views_settings__list_settings_html_erb__2294011647741628367_17629938240'
app/views/settings/_list_settings.html.erb:9:in `_app_views_settings__list_settings_html_erb__2294011647741628367_17629938240'
app/views/plugins/settings.html.erb:17:in`block in _app_views_plugins_settings_html_erb__4247434773900642039_17628814480'
app/views/plugins/settings.html.erb:16:in `_app_views_plugins_settings_html_erb__4247434773900642039_17628814480'
Request

Parameters:

{"id"=>"8"}

regards

**Comment by hulihanapplications** [comment]
K, good catch. This has been fixed in 85151f1 and pushed to dev. I also added an rspec test to cover this page so it should be checked during all future suite tests. Thanks!
