### ISSUE TITLE
Creating categories at top level

### ISSUE THREAD

**Issue by ghost** [hulihanapplications/Opal#21]
Hi, sorry, me again!

I can't seem to create categories at the top level, I get an error of:

There's 1 thing wrong with this category.
There were problems with the following things:

Parent Category cannot belong to itself.

I'm running on the dev branch.

Thanks

**Comment by hulihanapplications** [comment]
Thanks for reporting the bug. Should be fixed in bce3e86.

**Comment by ghost** [comment]
Many Thanks!

**Comment by hulihanapplications** [comment]
Sure thing! Let me know if you run into any other bugs.
